# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0003_auto_20191031_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Neighbour',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_image',
        ),
    ]
